const state={route:'home',category:'All',query:'',sort:'az',usbType:'All'};
const movieData=Array.isArray(movies)?movies.map(m=>({...m,type:'movie'})):[];
const seriesData=Array.isArray(series)?series.map(s=>({...s,type:'series'})):[];
const data=[...movieData,...seriesData];
const getCategories=item=>Array.isArray(item.categories)?item.categories:[];
const allCategories=[...new Set(categories)];
const usbTypes=Array.isArray(window.usbTypes)?window.usbTypes:["Old Blue USB","Blue USB","Black USB","Old Black USB","Red USB"];
const grid=document.getElementById('movieGrid'),empty=document.getElementById('emptyState');
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function usbClass(type=''){return type.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function usbBanner(item){return item.usbType?`<span class="usb-banner usb-${usbClass(item.usbType)}"><b>USB</b>${esc(item.usbType.replace(' USB',''))}</span>`:'';}
function filteredData(){return data.filter(m=>{const cats=getCategories(m);let match=state.category==='All'||cats.includes(state.category);if(state.route==='series')match=m.type==='series';if(state.usbType!=='All')match=match&&m.usbType===state.usbType;const q=state.query.toLowerCase();return match&&(!q||`${m.title} ${m.originalTitle||''} ${cats.join(' ')} ${(m.genres||[]).join(' ')} ${m.year||''} ${m.director||m.creator||''} ${m.usbType||''}`.toLowerCase().includes(q));}).sort((a,b)=>state.sort==='za'?b.title.localeCompare(a.title):state.sort==='year-new'?(b.year||0)-(a.year||0):state.sort==='year-old'?(a.year||0)-(b.year||0):a.title.localeCompare(b.title));}
function renderGrid(){const filtered=filteredData();grid.innerHTML=filtered.map(item=>{const cats=getCategories(item);const cover=item.cover&&!item.cover.includes('PASTE-')?`<img loading="lazy" src="${esc(item.cover)}" alt="${esc(item.title)} cover" onerror="this.style.display='none'">`:`<div class="fallback">${esc(item.title)}</div>`;const sub=item.type==='series'?`${item.year||'—'} · ${item.seasons||0} season${item.seasons===1?'':'s'}`:`${item.year||'—'} · ${item.status==='watched'?'Watched':'To watch'}`;return `<article class="movie-card" data-index="${data.indexOf(item)}" tabindex="0" role="button">${cover}<span class="movie-badge">${esc(cats[0]||'Uncategorised')}</span><span class="type-badge">${item.type==='series'?'Series':'Movie'}</span>${usbBanner(item)}<div class="movie-info"><h3>${esc(item.title)}</h3><p>${esc(sub)}</p></div></article>`;}).join('');empty.hidden=filtered.length!==0;grid.querySelectorAll('.movie-card').forEach(card=>{const open=()=>openTitle(Number(card.dataset.index));card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};});}
function renderHome(){const homeCats=['Action','Adventure','Comedy','Crime','Drama','Fantasy','Horror','Sci-Fi','Thriller','Superhero','Marvel','DC','Star Wars','Disney','Pixar','Harry Potter','James Bond','Fast & Furious','Jurassic Park','Transformers','John Wick','Christmas','British','Classics','Kids'];document.getElementById('homeCategoryGrid').innerHTML=homeCats.map(c=>`<button class="launch-card category-card-launch" data-route="category/${encodeURIComponent(c)}"><span>${esc(c)}</span><strong>${data.filter(m=>getCategories(m).includes(c)).length}</strong><small>titles</small></button>`).join('');document.getElementById('usbCards').innerHTML=usbTypes.map(t=>`<a class="usb-card usb-${usbClass(t)}" href="#usb/${encodeURIComponent(t)}"><span>USB</span><strong>${esc(t.replace(' USB',''))}</strong><small>${data.filter(m=>m.usbType===t).length} titles</small></a>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>location.hash=b.dataset.route);}
function renderSubFilters(){const wrap=document.getElementById('subFilters');if(state.category==='USB'){wrap.innerHTML=`<button class="filter-pill active" data-usb="All">All USBs</button>`+usbTypes.map(t=>`<button class="filter-pill usb-pill-${usbClass(t)}" data-usb="${esc(t)}">${esc(t)}</button>`).join('');wrap.querySelectorAll('[data-usb]').forEach(b=>b.onclick=()=>{state.usbType=b.dataset.usb;renderSubFilters();renderGrid();});}else{wrap.innerHTML='';}}
function renderRoute(){const home=document.getElementById('homePage'),lib=document.getElementById('libraryPage'),usb=document.getElementById('usbPage');home.hidden=lib.hidden=usb.hidden=true;const hash=location.hash.slice(1)||'home';state.query='';state.usbType='All';if(hash==='home'){home.hidden=false;return;}if(hash==='series'){state.route='series';state.category='All';document.getElementById('pageEyebrow').textContent='SERIES';document.getElementById('pageTitle').textContent='Series';document.getElementById('pageDescription').textContent='All of your series in one place.';lib.hidden=false;renderSubFilters();renderGrid();return;}if(hash.startsWith('usb/')){const t=decodeURIComponent(hash.slice(4));state.route='usb';state.category='USB';state.usbType=usbTypes.includes(t)?t:'All';document.getElementById('usbPageTitle').textContent=state.usbType==='All'?'USB Library':state.usbType;usb.hidden=false;renderUsbPage();return;}if(hash.startsWith('category/')){const c=decodeURIComponent(hash.slice(9));state.route='category';state.category=allCategories.includes(c)?c:'All';document.getElementById('pageEyebrow').textContent=state.category==='All'?'ALL TITLES':'CATEGORY';document.getElementById('pageTitle').textContent=state.category;document.getElementById('pageDescription').textContent=state.category==='All'?'Your complete movie and series library.':`Everything in the ${state.category} collection.`;lib.hidden=false;renderSubFilters();renderGrid();return;}location.hash='#home';}
function renderUsbPage(){const wrap=document.getElementById('usbPageGrid');const types=state.usbType==='All'?usbTypes:[state.usbType];wrap.innerHTML=types.map(t=>{const n=data.filter(m=>m.usbType===t).length;return `<a class="usb-large usb-${usbClass(t)}" href="#category/USB"><div><span>USB</span><h2>${esc(t.replace(' USB',''))}</h2><p>${n} titles</p></div><strong>→</strong></a>`;}).join('');}
function setText(id,v){document.getElementById(id).textContent=v||'—';}
function openTitle(index){const m=data[index];if(!m)return;const cats=getCategories(m);setText('detailTitle',m.title);setText('detailType',m.type==='series'?'Series':'Movie');setText('detailMeta',[m.year,m.runtime||m.episodeRuntime,m.ageRating,m.rating,m.status==='watched'?'Watched':'To watch'].filter(Boolean).join(' · '));setText('detailDescription',m.description);const cover=document.getElementById('detailCover');cover.src=m.cover||'';const back=document.getElementById('detailBackdrop');back.src=m.backdrop||m.cover||'';document.getElementById('detailUsb').innerHTML=m.usbType?usbBanner(m):'';document.getElementById('detailCategories').innerHTML=cats.map(c=>`<span>${esc(c)}</span>`).join('');document.getElementById('detailGenres').innerHTML=(m.genres||[]).map(g=>`<span>${esc(g)}</span>`).join('');const facts=[['Original title',m.originalTitle],['Release date',m.releaseDate],['Categories',cats.join(', ')],['Director / Creator',m.director||m.creator],['Studio / Network',m.studio||m.network],['Language',m.language],['Country',m.country],['Franchise',m.franchise],['Collection',m.collection],['USB collection',m.usbType],['Seasons',m.seasons],['Episodes',m.episodes],['Episode runtime',m.episodeRuntime]];document.getElementById('detailFacts').innerHTML=facts.filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=='').map(x=>`<div><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('');setText('detailCast',(m.cast||[]).join(', '));setText('detailNotes',m.notes);document.getElementById('detailNotesWrap').hidden=!m.notes;const modal=document.getElementById('movieModal');modal.hidden=false;modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
function closeMovie(){const modal=document.getElementById('movieModal');modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
document.querySelectorAll('[data-close-modal]').forEach(el=>el.onclick=closeMovie);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMovie();});document.getElementById('search').oninput=e=>{state.query=e.target.value;renderGrid();};document.getElementById('sort').onchange=e=>{state.sort=e.target.value;renderGrid();};document.getElementById('themeToggle').onclick=()=>document.body.classList.toggle('light');window.addEventListener('hashchange',renderRoute);
renderHome();renderRoute();